DELETE http://localhost:3001/api/persons/2

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
POST http://localhost:3001/api/persons
content-type: application/json

{
"name": "AB",
"number": "12-43-234345"
}
###

PUT http://localhost:3001/api/persons/641839cb2aeb1dc2e1b9dfd2
content-type: application/json

{
"name": "Danilo Abramov",
"number": "12-43-2343456"
}